# Generated by Django 3.2.4 on 2021-07-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ndc', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('labeler_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('finished', models.BooleanField()),
                ('listing_expiration_date', models.DateField()),
                ('active_ingredients', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drug.activeingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_ndc', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('marketing_start_date', models.DateField()),
                ('sample', models.BooleanField()),
                ('drug', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drug.drug')),
            ],
        ),
        migrations.CreateModel(
            name='OpenFDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.TextField(max_length=100)),
                ('rxcui', models.TextField(max_length=100)),
                ('unii', models.TextField(max_length=100)),
                ('spl_set_id', models.TextField(max_length=100)),
                ('drug', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drug.drug')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='openfda',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drug.openfda'),
        ),
        migrations.AddField(
            model_name='drug',
            name='packaging',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drug.packaging'),
        ),
        migrations.AddField(
            model_name='activeingredients',
            name='drug',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drug.drug'),
        ),
    ]
