# Generated by Django 3.2.4 on 2021-07-16 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpenFDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('rxcui', models.CharField(max_length=100)),
                ('unii', models.CharField(max_length=100)),
                ('spl_set_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_ndc', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('marketing_start_date', models.DateField()),
                ('sample', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ndc', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('labeler_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('finished', models.BooleanField()),
                ('listing_expiration_date', models.DateField()),
                ('marketing_category', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(max_length=100)),
                ('spl_id', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('marketing_start_date', models.DateField()),
                ('product_id', models.CharField(max_length=100)),
                ('application_number', models.CharField(max_length=100)),
                ('brand_name_base', models.CharField(max_length=100)),
                ('pharm_class', models.CharField(max_length=100)),
                ('active_ingredients', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drug.activeingredients', unique=True)),
                ('openfda', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drug.openfda', unique=True)),
                ('packaging', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drug.packaging', unique=True)),
            ],
        ),
    ]
