# Generated by Django 3.2.4 on 2021-07-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openfda',
            name='marketing_start_date',
        ),
        migrations.AlterField(
            model_name='openfda',
            name='manufacturer_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='openfda',
            name='rxcui',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='openfda',
            name='spl_set_id',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='openfda',
            name='unii',
            field=models.TextField(max_length=100),
        ),
    ]
